<a href="https://colab.research.google.com/github/orizay/free-fonts/blob/master/Python_Numpy(I).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python - Numpy(I)

## 라이브러리 - Overview
* 파이썬 코드에서 라이브러리 사용법

In [1]:
import numpy as np

In [10]:
A = np.array([1,2])
print(A)
print(type(A))

[1 2]
<class 'numpy.ndarray'>


# Numpy 
* => numpy는 머신러닝 코드 개발 할 경우 자주 사용되는 벡터, 행렬 등을 표현하고 연산할 때 반드시 필요한 라이브러리

* numpy vs list
  
   - => 머신러닝에서 숫자,사람,동물 등의 인식을 하기 위해서는 이미지(image)데이터를 행렬(matrix)로 변환하는 것이 중요함
   - => 행렬을 나타내기 위해서는 리스트(list)를 사용할 수도 있지만,행렬 연산이 직곽적이지 않고 오류 가능성이 높기 때문에 , 행렬 연산을 위새서는 numpy 사용이 필수임

In [11]:
# list 행렬 표현
A = [[1,0],[0,1]]
B = [[1,1],[1,1]]

A + B  # 행렬 연산이 아닌 리스트 연산

[[1, 0], [0, 1], [1, 1], [1, 1]]

In [13]:
A = np.array([[1,0], [0,1]])
B = np.array([[1,1] ,[1,1]])

A + B # 행렬 연사

array([[2, 1],
       [1, 2]])

# numpy vector(1차원 배열)
* 벡터(vector)생성 => vector는 np.array([...])를 사용하여 생성함
* 머신러닝 코드 구현 시 ,,연산을 위해서 vector,matrix등의 형상(shape), 차원(dimension)을 확인하는 것이 피요함

In [14]:
A = np.array([1,2,3])
B = np.array([4,5,6])

print(A,B)  #vector A,B출력

[1 2 3] [4 5 6]


In [15]:
# vector A, B형상 출력 => shape
print(A.shape, B.shape)

(3,) (3,)


In [16]:
# vector A, B 차원 출력 => ndim
print(A.ndim, B.ndim)

1 1


* vector 산술연산 => 벡터간 산술연산(+ , - , * , / )은 벡터의 각각의 원소에 대해서 행해짐

In [18]:
print(A + B)
print(A - B)
print(A * B)
print(A / B)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## matrix 행렬 생성
* => matrix 는 vector와 마찬가지로 np.array([...],[...],[...])를 사용하여 생성함

In [20]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[-1,-2,-3],[-4,-5,-6]])

# matrix A B 형상 출력 => shape
print(A.shape, B.shape)

# vector A, B 차원 출력 => ndim
print(A.ndim, B.ndim)

(2, 3) (2, 3)
2 2


* 형 변환(reshape) => vector 를 matrix 로 변경하거나 matrix를 다른 형상의 matrix로 변경하기 위해서는 reshape()사용하여 행렬의 shape을 변경하여야 함

In [21]:
# vector 생성
C = np.array([1,2,3])

In [22]:
# vector C 형상 출력 => shape
print(C.shape)

(3,)


In [23]:
# vector 를 (1,3) 행렬로 형 변환
C = C.reshape(1,3)
print(C.shape)

(1, 3)
